kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mxnetci/build.ubuntu_cpu_python
  commands:
  - pip3 install pyyaml docker
  - ./dev_menu.py menu 13
  - echo done

trigger:
  branch:
  - master
